export const defaultVoices = [
    { 
        id: 'sambert-zhinan-v1',
        name: '知楠', 
        gender: 'male', 
        description: '广告男声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20230713/cymq/知楠.wav',
        model: 'sambert-zhinan-v1',
        scenarios: ['通用场景'],
        language: '中文+英文',
        default_sample_rate: 48000,
        default_format: 'wav',
        is_custom: false
    },
    { 
        id: 'sambert-zhiqi-v1',
        name: '知琪', 
        gender: 'female', 
        description: '温柔女声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20230712/wnqs/知琪.wav',
        model: 'sambert-zhiqi-v1',
        scenarios: ['通用场景'],
        language: '中文+英文',
        default_sample_rate: 48000,
        default_format: 'wav',
        is_custom: false
    },
    { 
        id: 'sambert-zhichu-v1',
        name: '知厨', 
        gender: 'male', 
        description: '舌尖男声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20230712/enuf/知厨.wav',
        model: 'sambert-zhichu-v1',
        scenarios: ['新闻播报'],
        language: '中文+英文',
        default_sample_rate: 48000,
        default_format: 'wav',
        is_custom: false
    },
    { 
        id: 'sambert-zhide-v1',
        name: '知德', 
        gender: 'male', 
        description: '新闻男声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20230713/bfcm/知德.wav',
        model: 'sambert-zhide-v1',
        scenarios: ['新闻播报'],
        language: '中文+英文',
        default_sample_rate: 48000,
        default_format: 'wav',
        is_custom: false
    },
    { 
        id: 'sambert-zhijia-v1',
        name: '知佳', 
        gender: 'female', 
        description: '标准女声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20230712/acre/知佳.wav',
        model: 'sambert-zhijia-v1',
        scenarios: ['新闻播报'],
        language: '中文+英文',
        default_sample_rate: 48000,
        default_format: 'wav',
        is_custom: false
    },
    { 
        id: 'sambert-zhiru-v1',
        name: '知茹', 
        gender: 'female', 
        description: '新闻女声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20230712/motm/知茹.wav',
        model: 'sambert-zhiru-v1',
        scenarios: ['新闻播报'],
        language: '中文+英文',
        default_sample_rate: 48000,
        default_format: 'wav',
        is_custom: false
    },
    { 
        id: 'sambert-zhiqian-v1',
        name: '知倩', 
        gender: 'female', 
        description: '资讯女声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20230712/trye/知倩.wav',
        model: 'sambert-zhiqian-v1',
        scenarios: ['配音解说', '新闻播报'],
        language: '中文+英文',
        default_sample_rate: 48000,
        default_format: 'wav',
        is_custom: false
    },
    { 
        id: 'sambert-zhixiang-v1',
        name: '知祥', 
        gender: 'male', 
        description: '磁性男声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20230712/jdjf/知祥.wav',
        model: 'sambert-zhixiang-v1',
        scenarios: ['配音解说'],
        language: '中文+英文',
        default_sample_rate: 48000,
        default_format: 'wav',
        is_custom: false
    },
    { 
        id: 'sambert-zhiwei-v1',
        name: '知薇', 
        gender: 'female', 
        description: '萝莉女声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20230712/grnn/知薇.wav',
        model: 'sambert-zhiwei-v1',
        scenarios: ['阅读产品简介'],
        language: '中文+英文',
        default_sample_rate: 48000,
        default_format: 'wav',
        is_custom: false
    },
    { 
        id: 'sambert-zhihao-v1',
        name: '知浩', 
        gender: 'male', 
        description: '咨询男声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20230713/bmnx/知浩.wav',
        model: 'sambert-zhihao-v1',
        scenarios: ['通用场景'],
        language: '中文+英文',
        default_sample_rate: 16000,
        default_format: 'wav',
        is_custom: false
    },
    { 
        id: 'sambert-zhijing-v1',
        name: '知婧', 
        gender: 'female', 
        description: '严厉女声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20230713/lmgc/知婧.wav',
        model: 'sambert-zhijing-v1',
        scenarios: ['通用场景'],
        language: '中文+英文',
        default_sample_rate: 16000,
        default_format: 'wav',
        is_custom: false
    },
    { 
        id: 'sambert-zhiming-v1',
        name: '知茗', 
        gender: 'male', 
        description: '诙谐男声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20230713/enps/知茗.wav',
        model: 'sambert-zhiming-v1',
        scenarios: ['通用场景'],
        language: '中文+英文',
        default_sample_rate: 16000,
        default_format: 'wav',
        is_custom: false
    },
    { 
        id: 'sambert-beth-v1',
        name: 'Beth', 
        gender: 'female', 
        description: '咨询女声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20230713/zgct/Beth.wav',
        model: 'sambert-beth-v1',
        scenarios: ['通用场景'],
        language: '美式英文',
        default_sample_rate: 16000,
        default_format: 'wav',
        is_custom: false
    },
    { 
        id: 'sambert-betty-v1',
        name: 'Betty', 
        gender: 'female', 
        description: '客服女声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20230713/cshl/Betty.wav',
        model: 'sambert-betty-v1',
        scenarios: ['通用场景'],
        language: '美式英文',
        default_sample_rate: 16000,
        default_format: 'wav',
        is_custom: false
    },
    { 
        id: 'sambert-cally-v1',
        name: 'Cally', 
        gender: 'female', 
        description: '自然女声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20230713/ggtn/Cally.wav',
        model: 'sambert-cally-v1',
        scenarios: ['通用场景'],
        language: '美式英文',
        default_sample_rate: 16000,
        default_format: 'wav',
        is_custom: false
    }
]; 