export const defaultVoices = [
    { 
        id: 'longwan',
        name: '龙婉', 
        gender: 'female', 
        description: '标准女声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240830/dzkngm/%E9%BE%99%E5%A9%89.mp3',
        model: 'cosyvoice-v1',
        scenarios: ['语音助手', '导航播报', '聊天数字人'],
        language: '中文普通话',
        default_sample_rate: 22050,
        default_format: 'mp3',
        is_custom: false
    },
    { 
        id: 'longcheng',
        name: '龙橙', 
        gender: 'female', 
        description: '标准女声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240830/ggjwfl/%E9%BE%99%E6%A9%99.wav',
        model: 'cosyvoice-v1',
        scenarios: ['语音助手', '导航播报', '聊天数字人'],
        language: '中文普通话',
        default_sample_rate: 22050,
        default_format: 'mp3',
        is_custom: false
    },
    { 
        id: 'longhua',
        name: '龙华', 
        gender: 'female', 
        description: '标准女声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240830/jpjtvy/%E9%BE%99%E5%8D%8E.wav',
        model: 'cosyvoice-v1',
        scenarios: ['语音助手', '导航播报', '聊天数字人'],
        language: '中文普通话',
        default_sample_rate: 22050,
        default_format: 'mp3',
        is_custom: false
    },
    { 
        id: 'longxiaochun',
        name: '龙小淳', 
        gender: 'female', 
        description: '活力女声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/rlfvcd/%E9%BE%99%E5%B0%8F%E6%B7%B3.mp3',
        model: 'cosyvoice-v1',
        scenarios: ['语音助手', '导航播报', '聊天数字人'],
        language: '中文+英文',
        default_sample_rate: 22050,
        default_format: 'mp3',
        is_custom: false
    },
    { 
        id: 'longxiaoxia',
        name: '龙小夏', 
        gender: 'female', 
        description: '温柔女声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/wzywtu/%E9%BE%99%E5%B0%8F%E5%A4%8F.mp3',
        model: 'cosyvoice-v1',
        scenarios: ['语音助手', '聊天数字人'],
        language: '中文',
        default_sample_rate: 22050,
        default_format: 'mp3',
        is_custom: false
    },
    { 
        id: 'longxiaocheng',
        name: '龙小诚', 
        gender: 'male', 
        description: '温柔男声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/xrqksx/%E9%BE%99%E5%B0%8F%E8%AF%9A.mp3',
        model: 'cosyvoice-v1',
        scenarios: ['语音助手', '导航播报', '聊天数字人'],
        language: '中文+英文',
        default_sample_rate: 22050,
        default_format: 'mp3',
        is_custom: false
    },
    { 
        id: 'longxiaobai',
        name: '龙小白', 
        gender: 'female', 
        description: '甜美女声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/vusvze/%E9%BE%99%E5%B0%8F%E7%99%BD.mp3',
        model: 'cosyvoice-v1',
        scenarios: ['聊天数字人', '有声书', '语音助手'],
        language: '中文',
        default_sample_rate: 22050,
        default_format: 'mp3',
        is_custom: false
    },
    { 
        id: 'longlaotie',
        name: '龙老铁', 
        gender: 'male', 
        description: '东北口音男声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/pfsfir/%E9%BE%99%E8%80%81%E9%93%81.mp3',
        model: 'cosyvoice-v1',
        scenarios: ['新闻播报', '有声书', '语音助手', '直播带货', '导航播报'],
        language: '中文东北口音',
        default_sample_rate: 22050,
        default_format: 'mp3',
        is_custom: false
    },
    { 
        id: 'longshu',
        name: '龙书', 
        gender: 'male', 
        description: '成熟男声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/azcerd/%E9%BE%99%E4%B9%A6.mp3',
        model: 'cosyvoice-v1',
        scenarios: ['有声书', '语音助手', '导航播报', '新闻播报', '智能客服'],
        language: '中文',
        default_sample_rate: 22050,
        default_format: 'mp3',
        is_custom: false
    },
    { 
        id: 'longshuo',
        name: '龙硕', 
        gender: 'male', 
        description: '浑厚男声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/lcykpl/%E9%BE%99%E7%A1%95.mp3',
        model: 'cosyvoice-v1',
        scenarios: ['语音助手', '导航播报', '新闻播报', '客服催收'],
        language: '中文',
        default_sample_rate: 22050,
        default_format: 'mp3',
        is_custom: false
    },
    { 
        id: 'longjing',
        name: '龙婧', 
        gender: 'female', 
        description: '知性女声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/ozkbmb/%E9%BE%99%E5%A9%A7.mp3',
        model: 'cosyvoice-v1',
        scenarios: ['语音助手', '导航播报', '新闻播报', '客服催收'],
        language: '中文',
        default_sample_rate: 22050,
        default_format: 'mp3',
        is_custom: false
    },
    { 
        id: 'longmiao',
        name: '龙妙', 
        gender: 'female', 
        description: '元气女声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/zjnqis/%E9%BE%99%E5%A6%99.mp3',
        model: 'cosyvoice-v1',
        scenarios: ['客服催收', '导航播报', '有声书', '语音助手'],
        language: '中文',
        default_sample_rate: 22050,
        default_format: 'mp3',
        is_custom: false
    },
    { 
        id: 'longyue',
        name: '龙悦', 
        gender: 'female', 
        description: '温婉女声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/nrkjqf/%E9%BE%99%E6%82%A6.mp3',
        model: 'cosyvoice-v1',
        scenarios: ['语音助手', '诗词朗诵', '有声书朗读', '导航播报', '新闻播报', '客服催收'],
        language: '中文',
        default_sample_rate: 22050,
        default_format: 'mp3',
        is_custom: false
    },
    { 
        id: 'longyuan',
        name: '龙媛', 
        gender: 'female', 
        description: '柔美女声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/xuboos/%E9%BE%99%E5%AA%9B.mp3',
        model: 'cosyvoice-v1',
        scenarios: ['有声书', '语音助手', '聊天数字人'],
        language: '中文',
        default_sample_rate: 22050,
        default_format: 'mp3',
        is_custom: false
    },
    { 
        id: 'longfei',
        name: '龙飞', 
        gender: 'male', 
        description: '沉稳男声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/bhkjjx/%E9%BE%99%E9%A3%9E.mp3',
        model: 'cosyvoice-v1',
        scenarios: ['会议播报', '新闻播报', '有声书'],
        language: '中文',
        default_sample_rate: 22050,
        default_format: 'mp3',
        is_custom: false
    },
    { 
        id: 'longjielidou',
        name: '龙杰力豆', 
        gender: 'male', 
        description: '少年男声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/dctiyg/%E9%BE%99%E6%9D%B0%E5%8A%9B%E8%B1%86.mp3',
        model: 'cosyvoice-v1',
        scenarios: ['新闻播报', '有声书', '聊天助手'],
        language: '中文+英文',
        default_sample_rate: 22050,
        default_format: 'mp3',
        is_custom: false
    },
    { 
        id: 'longtong',
        name: '龙彤', 
        gender: 'female', 
        description: '甜美女声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/qyqmvo/%E9%BE%99%E5%BD%A4.mp3',
        model: 'cosyvoice-v1',
        scenarios: ['有声书', '导航播报', '聊天数字人'],
        language: '中文',
        default_sample_rate: 22050,
        default_format: 'mp3',
        is_custom: false
    },
    { 
        id: 'longxiang',
        name: '龙祥', 
        gender: 'male', 
        description: '稳重男声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/jybshd/%E9%BE%99%E7%A5%A5.mp3',
        model: 'cosyvoice-v1',
        scenarios: ['新闻播报', '有声书', '导航播报'],
        language: '中文',
        default_sample_rate: 22050,
        default_format: 'mp3',
        is_custom: false
    },
    { 
        id: 'loongstella',
        name: 'Stella', 
        gender: 'female', 
        description: '英文女声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/haffms/Stella.mp3',
        model: 'cosyvoice-v1',
        scenarios: ['语音助手', '直播带货', '导航播报', '客服催收', '有声书'],
        language: '中文+英文',
        default_sample_rate: 22050,
        default_format: 'mp3',
        is_custom: false
    },
    { 
        id: 'loongbella',
        name: 'Bella', 
        gender: 'female', 
        description: '中英文女声',
        sample_url: 'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/tguine/Bella.mp3',
        model: 'cosyvoice-v1',
        scenarios: ['语音助手', '客服催收', '新闻播报', '导航播报'],
        language: '中文',
        default_sample_rate: 22050,
        default_format: 'mp3',
        is_custom: false
    }
]; 